### ISSUE TITLE
Add travis CI to the project for easy deployments

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-repl-backend#4]
Currently, we can deploy by running ``yarn deploy`` from the local machine. We can automate it by adding travis.

**Comment by Utwo** [comment]
For the moment I've set up Cloud Build from Google, because it's integrates easily with Cloud functions. In the future we can investigate in Azure Pipeline or Travis because Cloud Build doesn't have a public dashboard.
